services:
  task-api:
    build:
      context: ./src
      dockerfile: API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/app.db
      - ASPNETCORE_HTTP_PORTS=8080
    volumes:
      - ./data:/app/data
